source 'https://github.com/Cocoapods/Specs.git'
platform :ios, '8.0'

xcodeproj 'office365-e2end-tests'
pod 'ADALIOS', '~> 1.2.2' # 1.0.0 < ver < 1.2.3
pod 'Office365', :git => 'https://github.com/OfficeDev/Office-365-SDK-for-iOS', :branch => 'dev'
pod 'LiveSDK'